"use client";

import { useMemo, useState } from "react";
import { Search, ShieldAlert, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { Customer } from "@/types/domain";

export function CustomersTable({ customers }: { customers: Customer[] }) { const [query,setQuery]=useState(""); const rows=useMemo(()=>customers.filter((customer)=>`${customer.firstName} ${customer.lastName} ${customer.phone} ${customer.email}`.toLowerCase().includes(query.toLowerCase())),[customers,query]); return <><div className="mb-4 flex items-center gap-3 rounded-xl border bg-card p-3"><Search className="ml-2 size-4 text-muted-foreground" /><Input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Cerca per nome, telefono o email…" className="border-0 bg-background" /><Badge variant="outline" className="hidden sm:inline-flex">{rows.length} profili</Badge></div><div className="overflow-hidden rounded-xl border bg-card"><Table><TableHeader><TableRow><TableHead>Ospite</TableHead><TableHead>Classificazione</TableHead><TableHead>Visite</TableHead><TableHead>Preferenze e rischi</TableHead><TableHead>Consensi</TableHead></TableRow></TableHeader><TableBody>{rows.map((customer)=><TableRow key={customer.id}><TableCell><p className="font-medium">{customer.firstName} {customer.lastName}</p><p className="mt-1 text-xs text-muted-foreground">{customer.phone} · {customer.email ?? "email assente"}</p></TableCell><TableCell><Badge variant={customer.customerType === "vip" ? "default" : "secondary"}>{customer.customerType === "vip" && <Sparkles />}{customer.customerType}</Badge></TableCell><TableCell><span className="font-mono">{customer.totalBookings}</span><p className="mt-1 text-xs text-muted-foreground">{customer.noShowCount} no-show</p></TableCell><TableCell>{customer.allergies ? <span className="inline-flex items-center gap-2 text-sm text-amber-300"><ShieldAlert className="size-4" />{customer.allergies}</span> : customer.accessibilityNeeds ? <span className="text-sm">{customer.accessibilityNeeds}</span> : <span className="text-muted-foreground">—</span>}</TableCell><TableCell><p className="text-xs">Privacy {customer.privacyConsent ? "✓" : "—"}</p><p className="mt-1 text-xs text-muted-foreground">Marketing {customer.marketingConsent ? "✓" : "—"}</p></TableCell></TableRow>)}</TableBody></Table></div></>; }

