"use client";

import { useState } from "react";
import { Check, Clock3, LoaderCircle, MessageSquareText, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { WaitlistEntry } from "@/types/domain";
import { formatTimeInZone } from "@/lib/datetime";

export function WaitlistBoard({ initialEntries }: { initialEntries: WaitlistEntry[] }) {
  const [entries, setEntries] = useState(initialEntries); const [pending, setPending] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  async function update(id: string, status: WaitlistEntry["status"]) { setPending(id); setError(null); const response = await fetch("/api/admin/v1/waitlist", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, status }) }); const payload = await response.json() as { data?: WaitlistEntry; error?: { message: string } }; if (payload.data) setEntries((current) => current.map((entry) => entry.id === id ? payload.data! : entry)); else setError(payload.error?.message ?? "Aggiornamento non riuscito."); setPending(null); }
  return <div className="grid gap-5 lg:grid-cols-3">{["waiting","offered","converted"].map((status) => <section key={status} className="rounded-xl border bg-card"><div className="flex items-center justify-between border-b px-4 py-3"><h2 className="font-heading text-lg">{status === "waiting" ? "In attesa" : status === "offered" ? "Offerta inviata" : "Convertiti"}</h2><Badge variant="secondary">{entries.filter((entry) => entry.status === status).length}</Badge></div><div className="space-y-3 p-3">{entries.filter((entry) => entry.status === status).map((entry) => <article key={entry.id} className="rounded-lg border bg-background p-4"><div className="flex justify-between gap-3"><div><p className="font-medium">{entry.customer.firstName} {entry.customer.lastName}</p><p className="mt-1 text-xs text-muted-foreground">{entry.partySize} ospiti · {formatTimeInZone(entry.requestedStartAt)} ± {entry.flexibilityMinutes} min</p></div><span className="font-mono text-xs text-muted-foreground">P{entry.priority}</span></div><div className="mt-4 flex gap-2">{status === "waiting" && <Button size="sm" onClick={() => update(entry.id,"offered")} disabled={pending === entry.id}>{pending === entry.id ? <LoaderCircle className="animate-spin" /> : <MessageSquareText />}Offri tavolo</Button>}{status === "offered" && <Button size="sm" onClick={() => update(entry.id,"converted")} disabled={pending === entry.id}><Check />Converti</Button>}{status !== "converted" && <Button size="sm" variant="ghost" onClick={() => update(entry.id,"cancelled")}><X />Rimuovi</Button>}</div></article>)}{!entries.some((entry) => entry.status === status) && <div className="py-12 text-center text-xs text-muted-foreground"><Clock3 className="mx-auto mb-2 size-5" />Nessuna voce</div>}</div></section>)}{error && <p role="alert" className="lg:col-span-3 rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}</div>;
}
