import { Bot, PhoneForwarded, PhoneIncoming } from "lucide-react";
import { PageHeading } from "@/components/admin/page-heading";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { requirePermission } from "@/lib/auth/dal";
import { formatTimeInZone } from "@/lib/datetime";
import { getRepository } from "@/repositories";
import { getActiveAdminLocation } from "@/lib/admin/location";
export default async function CallsPage(){await requirePermission("calls:read");const location=await getActiveAdminLocation();const calls=await getRepository(location.id).listCalls();const completed=calls.filter((call)=>call.status==="completed").length;return <><PageHeading eyebrow={location.shortName} title="Chiamate" description={`Trascrizioni, intenti ed escalation del canale telefonico di ${location.city}.`}/><div className="mb-6 grid gap-px overflow-hidden rounded-xl border bg-border sm:grid-cols-3"><Stat icon={<PhoneIncoming/>} label="Chiamate" value={calls.length}/><Stat icon={<Bot/>} label="Concluse dall'AI" value={completed}/><Stat icon={<PhoneForwarded/>} label="Escalation" value={calls.filter((call)=>call.humanEscalationRequired).length}/></div><div className="overflow-hidden rounded-xl border bg-card"><Table><TableHeader><TableRow><TableHead>Ora</TableHead><TableHead>Numero</TableHead><TableHead>Intento</TableHead><TableHead>Esito</TableHead><TableHead>Durata</TableHead><TableHead>Stato</TableHead></TableRow></TableHeader><TableBody>{calls.map((call)=><TableRow key={call.id}><TableCell className="font-mono">{formatTimeInZone(call.startedAt)}</TableCell><TableCell>{call.callerPhone}</TableCell><TableCell>{call.intent}</TableCell><TableCell><p>{call.outcome}</p><p className="mt-1 max-w-sm truncate text-xs text-muted-foreground">{call.summary}</p></TableCell><TableCell className="font-mono">{Math.floor(call.durationSeconds/60)}:{String(call.durationSeconds%60).padStart(2,"0")}</TableCell><TableCell><Badge variant={call.humanEscalationRequired?"destructive":"secondary"}>{call.humanEscalationRequired?"Richiamare":"Completata"}</Badge></TableCell></TableRow>)}</TableBody></Table></div></>}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <Card className="rounded-none border-0"><CardContent className="flex items-center gap-4 p-5"><span className="text-primary [&_svg]:size-5">{icon}</span><div><p className="text-2xl font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div></CardContent></Card>}
